name: Build Windows

on:
  workflow_call:
    inputs:
      unreal-engine-version:
        required: true
        type: string
      unreal-runner-label:
        required: true
        type: string
      unreal-engine-zip:
        required: true
        type: string
      unreal-linux-toolchain:
        required: false
        type: string
        default: ""
      unreal-path:
        required: true
        type: string
      upload-package-base-name:
        required: true
        type: string
jobs:
  build:
    runs-on: ["self-hosted","windows","x64","${{ inputs.unreal-runner-label }}"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # so that `git describe` works.
      - name: Install dependencies
        run: |
          choco install -y dotnetcore-sdk wget
      - name: Install Unreal Engine
        run: |
          mkdir -p "D:/Program Files/Epic Games"
          aws s3 cp "${{ inputs.unreal-engine-zip }}" "D:/Program Files/Epic Games/UE.zip"
          7z x "D:/Program Files/Epic Games/UE.zip" "-oD:/Program Files/Epic Games/"
          del "D:/Program Files/Epic Games/UE.zip"
          Start-Process "${{ inputs.unreal-path }}/Engine/Extras/Redist/en-us/UEPrereqSetup_x64.exe" -Args "-q" -Wait
      - name: Install Unreal Engine Linux Toolchain
        if: ${{ inputs.unreal-linux-toolchain != "" }}
        run: |
          wget "${{ inputs.unreal-linux-toolchain }}" "${env:GITHUB_WORKSPACE}/linux-toolchain.exe"
          Start-Process "${env:GITHUB_WORKSPACE}/linux-toolchain.exe" -Args "/S" -Wait
          del "${env:GITHUB_WORKSPACE}/linux-toolchain.exe"
      - name: Set environment variables
        run: |
          $env:CESIUM_UNREAL_VERSION=$(git describe)
          $env:BUILD_CESIUM_UNREAL_PACKAGE_NAME="${{ inputs.upload-package-base-name }}-${env:CESIUM_UNREAL_VERSION}"
          $env:BUILD_CESIUM_UNREAL_PACKAGE_PATH="$env:GITHUB_WORKSPACE/packages/CesiumForUnreal"
          $env:UNREAL_BATCH_FILES_PATH="${{ inputs.unreal-path }}/Engine/Build/BatchFiles"

          # Make these available to subsequent steps
          echo "BUILD_CESIUM_UNREAL_PACKAGE_NAME=${env:BUILD_CESIUM_UNREAL_PACKAGE_NAME}" >> $env:GITHUB_ENV
          echo "BUILD_CESIUM_UNREAL_PACKAGE_PATH=${env:BUILD_CESIUM_UNREAL_PACKAGE_PATH}" >> $env:GITHUB_ENV
          echo "UNREAL_BATCH_FILES_PATH=${env:UNREAL_BATCH_FILES_PATH}" >> $env:GITHUB_ENV

          # Confirm vars to the console
          echo ""
          echo BUILD_CESIUM_UNREAL_PACKAGE_NAME=$env:BUILD_CESIUM_UNREAL_PACKAGE_NAME
          echo BUILD_CESIUM_UNREAL_PACKAGE_PATH=$env:BUILD_CESIUM_UNREAL_PACKAGE_PATH
          echo UNREAL_BATCH_FILES_PATH=$env:UNREAL_BATCH_FILES_PATH
      - name: Install nasm
        uses: ilammy/setup-nasm@v1.4.0
      - name: Build cesium-native
        run: |
          cd extern
          cmake -B build -S . -A x64
          cmake --build build --config Release --target install -j8
      - name: Overwrite plugin engine version
        run: |
          ((Get-Content -path CesiumForUnreal.uplugin -Raw) -replace '"EngineVersion": "5.0.0"','"EngineVersion": "${{ inputs.unreal-engine-version }}"') | Set-Content -Path CesiumForUnreal.uplugin
      - name: Build CesiumForUnreal plugin
        timeout-minutes: 120
        run: |
          cd "$env:UNREAL_BATCH_FILES_PATH"
          ./RunUAT.bat BuildPlugin -Plugin="$env:GITHUB_WORKSPACE/CesiumForUnreal.uplugin" -Package="$env:BUILD_CESIUM_UNREAL_PACKAGE_PATH" -CreateSubFolder -TargetPlatforms=Win64
      - name: Upload plugin artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_CESIUM_UNREAL_PACKAGE_NAME}}
          path: packages
